server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath*:com/next/jiangzh/**/xml/*Mapper.xml
  global-config:
    id-type: 0  #0:���ݿ�ID����   1:�û�����id  2:ȫ��Ψһid(IdWorker)  3:ȫ��ΨһID(uuid)
    db-column-underline: false
    refresh-mapper: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/next_film?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat


logging:
  level.root: info
  level.com.next.jiangzh: debug
  path: logs/
  file: next-film.log